### ISSUE TITLE
Wireguard-rs on crates.io

### ISSUE THREAD

**Issue by Ange-Cesari** [DefGuard/wireguard-rs#10]
Hi,

Would it possible to maintain Wireguard-rs on crates.io and doc.rs so it's accessible directly as a pull in the cargo.toml instead of git cloning the entire repository and manually adding cloned folder's path?

Whether it's already on crates.io or not, would it be possible to provide a link in the github to the crate when it's ready ?

Thanks,
Ange

**Comment by wojcik91** [comment]
@Ange-Cesari We've just published the initial version on crates.io. You can find it [here](https://crates.io/crates/defguard_wireguard_rs).
