### ISSUE TITLE
Presharedkey support 

### ISSUE THREAD

**Issue by Ange-Cesari** [DefGuard/wireguard-rs#11]
Hi,

I couldn't see any code related to the presharedkey for the server (nor the client) 

Is it supported ?

If so, would it be possible to provide a example with presharedkey support ?

If it's supported by the library but not implemented yet (macros, public function...), do you think it's possible to provide an example of how to create the presharedkey with dalek and write to the api ?

Thanks,
Ange

**Comment by teon** [comment]
Right now we do not support pre-shared key, but we will put this on the roadmap.

**Comment by Ange-Cesari** [comment]
Hi @teon

Would it be possible to have a link to that roadmap ? I couldn't find it on github. Is it public ?

Best,
Ange

**Comment by master-hax** [comment]
fwiw i'm using this as a workaround at the moment:
```
let mut file = NamedTempFile::new()?;
writeln!(file, "{}", preshared_key.to_string());
let path = file.into_temp_path();
println!("wrote psk to file {:#?}", path);

let output = std::process::Command::new("wg")
.args(["set", interface_name, "peer", &peer_public_key.to_string(), "preshared-key", path.to_str().unwrap()])
.output()?;

path.close()?;
```

**Comment by wojcik91** [comment]
Hi @Ange-Cesari & @master-hax!
I did not have time to look into this yet, but from what I know the [`Peer`](https://docs.rs/defguard_wireguard_rs/0.2.1/defguard_wireguard_rs/host/struct.Peer.html) struct already includes an optional `preshared_key` field.

Did you try it out?

**Comment by master-hax** [comment]
> Hi @Ange-Cesari & @master-hax!
> I did not have time to look into this yet, but from what I know the [`Peer`](https://docs.rs/defguard_wireguard_rs/0.2.1/defguard_wireguard_rs/host/struct.Peer.html) struct already includes an optional `preshared_key` field.
> 
> Did you try it out?

Yes I've tried it out.

The key passed to the struct is persisted and looks like it gets applied when the interface configurationis read back.

However if we double check the peer with `wg show`we can see that the preshared key is not set.

**Comment by Ange-Cesari** [comment]
Hey, @wojcik91 

I tried too, 

It seems it's not a structure issue, it's an interface configuration issue and more like how are applied the different fields

**Comment by wojcik91** [comment]
Hi.
There was indeed a bug in Linux implementation. Should be resolved now by https://github.com/DefGuard/wireguard-rs/pull/21. I'll make a new patch release shortly.
