### ISSUE TITLE
Unable to change existing WireGuard interface address on Linux

### ISSUE THREAD

**Issue by wojcik91** [DefGuard/wireguard-rs#17]
When updating the address (for example from 10.0.70.1/24 to 10.0.70.10/24) the IP is not actually changed when running on Linux.
The interface has to be removed first, then it can be reconfigured.

**Comment by Ange-Cesari** [comment]
Hey @wojcik91 ,

What address are you refering to ?

Is that the address of the host or any/peer address ?

I thought using the configure_interface() was working

Best,
Ange

**Comment by moubctez** [comment]
Fixed in #63
